<?php

/**
 * @file
 * A block module that displays latest news.
 */
 
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function latest_news_help($path, $arg) {
  switch ($path) {
    case "admin/help#latest_news":
      return '' . t("Displays links to news created on this date") . '';
      break;
  }
} 

/**
 * Implements hook_block_info().
 */
function latest_news_block_info() {
  $blocks['latest_news'] = array(
    // The name that will appear in the block list.
    'info' => t('Latest News'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Custom content function. 
 * 
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 * 
 * @return 
 *   A result set of the targeted posts.
 */
function latest_news_contents(){
  //Get today's date.
  $today = getdate();
  //Calculate the date a week ago.
  $start_time = mktime(0, 0, 0,$today['mon'],($today['mday'] - 21), $today['year']);
  //Get all posts from one week ago to the present.
  $end_time = time();
  
  $max_num = variable_get('latest_news_max', 3);
  
   $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1) //Published.
    ->condition('n.type', 'article')
    ->condition('created', array($start_time, $end_time), 'BETWEEN')
    ->orderBy('created', 'DESC') //Most recent first.
    ->range(0, $max_num)
    ->execute(); 
  return $query;  
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function latest_news_block_view($delta = '') {
  switch ($delta) {
    case 'latest_news':
      $block['subject'] = t('Latest News');
      if (user_access('access content')) {
        // Use our custom function to retrieve data.
        $result = latest_news_contents();
        // Array to contain items for the block to render.
        $items = array();
        // Iterate over the resultset and format as links.
        foreach ($result as $node) {
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          ); 
        }
       // No content in the last week.
        if (empty($items)) {
          $block['content'] = t('No posts available.');  
        } 
        else {
          // Pass data through theme function.
          $block['content'] = theme('item_list', array(
            'items' => $items));
        }
      }
    return $block;
  }
  
}
/**
 * Implements hook_menu().
 */
function latest_news_menu() {
  $items = array();

  $items['admin/config/content/latest_news'] = array(
    'title' => 'Latest News',
    'description' => 'Configuration for Latest News module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('latest_news_form'),
    'access arguments' => array('access latest_news content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: Current posts settings
 *
 * @see latest_news_menu()
 */
function latest_news_form($form, &$form_state) {
  $form['latest_news_max'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of news'),
    '#default_value' => variable_get('latest_news_max', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('The maximum number of links to display in the block.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements validation from the Form API.
 * 
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state 
 *   during processing.
 */
function latest_news_form_validate($form, &$form_state){
  $max_num = $form_state['values']['latest_news_max'];
  if (!is_numeric($max_num)){
    form_set_error('latest_news_max', t('You must enter a number for the maximum number of news to display.'));
  }
  elseif ($max_num <= 0){
    form_set_error('latest_news_max', t('Maximum number of news to display must be positive.'));
  }
}

/**
 * Implements hook_permission().
 */
function latest_news_permission() {
  return array(
    'access latest_news content' => array(
      'title' => t('Access content for the Latest news module'),
    )
  );
}

